//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.1 版自动生成。
// 
#pragma warning disable 1591

namespace immmclient.cn.imaimaimai.www {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="immmSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TopObject))]
    public partial class immm : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchCouponOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchCouponRSOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTaoCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetItemDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetItemDetailJsonOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public immm() {
            this.Url = global::immmclient.Properties.Settings.Default.immm_cn_imaimaimai_www_immm;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event SearchCouponCompletedEventHandler SearchCouponCompleted;
        
        /// <remarks/>
        public event SearchCouponRSCompletedEventHandler SearchCouponRSCompleted;
        
        /// <remarks/>
        public event GetTaoCodeCompletedEventHandler GetTaoCodeCompleted;
        
        /// <remarks/>
        public event GetItemDetailCompletedEventHandler GetItemDetailCompleted;
        
        /// <remarks/>
        public event GetItemDetailJsonCompletedEventHandler GetItemDetailJsonCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SearchCoupon", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SearchCoupon(string words, long pageNo, long PageSize) {
            object[] results = this.Invoke("SearchCoupon", new object[] {
                        words,
                        pageNo,
                        PageSize});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SearchCouponAsync(string words, long pageNo, long PageSize) {
            this.SearchCouponAsync(words, pageNo, PageSize, null);
        }
        
        /// <remarks/>
        public void SearchCouponAsync(string words, long pageNo, long PageSize, object userState) {
            if ((this.SearchCouponOperationCompleted == null)) {
                this.SearchCouponOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchCouponOperationCompleted);
            }
            this.InvokeAsync("SearchCoupon", new object[] {
                        words,
                        pageNo,
                        PageSize}, this.SearchCouponOperationCompleted, userState);
        }
        
        private void OnSearchCouponOperationCompleted(object arg) {
            if ((this.SearchCouponCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchCouponCompleted(this, new SearchCouponCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SearchCouponRS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TbkCouponDomain[] SearchCouponRS(string words, long pageNo, long PageSize) {
            object[] results = this.Invoke("SearchCouponRS", new object[] {
                        words,
                        pageNo,
                        PageSize});
            return ((TbkCouponDomain[])(results[0]));
        }
        
        /// <remarks/>
        public void SearchCouponRSAsync(string words, long pageNo, long PageSize) {
            this.SearchCouponRSAsync(words, pageNo, PageSize, null);
        }
        
        /// <remarks/>
        public void SearchCouponRSAsync(string words, long pageNo, long PageSize, object userState) {
            if ((this.SearchCouponRSOperationCompleted == null)) {
                this.SearchCouponRSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchCouponRSOperationCompleted);
            }
            this.InvokeAsync("SearchCouponRS", new object[] {
                        words,
                        pageNo,
                        PageSize}, this.SearchCouponRSOperationCompleted, userState);
        }
        
        private void OnSearchCouponRSOperationCompleted(object arg) {
            if ((this.SearchCouponRSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchCouponRSCompleted(this, new SearchCouponRSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTaoCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTaoCode(string url, string logourl, string infoText) {
            object[] results = this.Invoke("GetTaoCode", new object[] {
                        url,
                        logourl,
                        infoText});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTaoCodeAsync(string url, string logourl, string infoText) {
            this.GetTaoCodeAsync(url, logourl, infoText, null);
        }
        
        /// <remarks/>
        public void GetTaoCodeAsync(string url, string logourl, string infoText, object userState) {
            if ((this.GetTaoCodeOperationCompleted == null)) {
                this.GetTaoCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTaoCodeOperationCompleted);
            }
            this.InvokeAsync("GetTaoCode", new object[] {
                        url,
                        logourl,
                        infoText}, this.GetTaoCodeOperationCompleted, userState);
        }
        
        private void OnGetTaoCodeOperationCompleted(object arg) {
            if ((this.GetTaoCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTaoCodeCompleted(this, new GetTaoCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetItemDetail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public NTbkItem[] GetItemDetail(string ids) {
            object[] results = this.Invoke("GetItemDetail", new object[] {
                        ids});
            return ((NTbkItem[])(results[0]));
        }
        
        /// <remarks/>
        public void GetItemDetailAsync(string ids) {
            this.GetItemDetailAsync(ids, null);
        }
        
        /// <remarks/>
        public void GetItemDetailAsync(string ids, object userState) {
            if ((this.GetItemDetailOperationCompleted == null)) {
                this.GetItemDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetItemDetailOperationCompleted);
            }
            this.InvokeAsync("GetItemDetail", new object[] {
                        ids}, this.GetItemDetailOperationCompleted, userState);
        }
        
        private void OnGetItemDetailOperationCompleted(object arg) {
            if ((this.GetItemDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetItemDetailCompleted(this, new GetItemDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetItemDetailJson", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetItemDetailJson(string ids) {
            object[] results = this.Invoke("GetItemDetailJson", new object[] {
                        ids});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetItemDetailJsonAsync(string ids) {
            this.GetItemDetailJsonAsync(ids, null);
        }
        
        /// <remarks/>
        public void GetItemDetailJsonAsync(string ids, object userState) {
            if ((this.GetItemDetailJsonOperationCompleted == null)) {
                this.GetItemDetailJsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetItemDetailJsonOperationCompleted);
            }
            this.InvokeAsync("GetItemDetailJson", new object[] {
                        ids}, this.GetItemDetailJsonOperationCompleted, userState);
        }
        
        private void OnGetItemDetailJsonOperationCompleted(object arg) {
            if ((this.GetItemDetailJsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetItemDetailJsonCompleted(this, new GetItemDetailJsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TbkCouponDomain : TopObject {
        
        private long categoryField;
        
        private string commission_rateField;
        
        private string coupon_click_urlField;
        
        private string coupon_end_timeField;
        
        private string coupon_infoField;
        
        private long coupon_remain_countField;
        
        private string coupon_start_timeField;
        
        private long coupon_total_countField;
        
        private string item_descriptionField;
        
        private string item_urlField;
        
        private string nickField;
        
        private long num_iidField;
        
        private string pict_urlField;
        
        private long seller_idField;
        
        private string shop_titleField;
        
        private string[] small_imagesField;
        
        private string titleField;
        
        private long user_typeField;
        
        private long volumeField;
        
        private string zk_final_priceField;
        
        /// <remarks/>
        public long category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public string commission_rate {
            get {
                return this.commission_rateField;
            }
            set {
                this.commission_rateField = value;
            }
        }
        
        /// <remarks/>
        public string coupon_click_url {
            get {
                return this.coupon_click_urlField;
            }
            set {
                this.coupon_click_urlField = value;
            }
        }
        
        /// <remarks/>
        public string coupon_end_time {
            get {
                return this.coupon_end_timeField;
            }
            set {
                this.coupon_end_timeField = value;
            }
        }
        
        /// <remarks/>
        public string coupon_info {
            get {
                return this.coupon_infoField;
            }
            set {
                this.coupon_infoField = value;
            }
        }
        
        /// <remarks/>
        public long coupon_remain_count {
            get {
                return this.coupon_remain_countField;
            }
            set {
                this.coupon_remain_countField = value;
            }
        }
        
        /// <remarks/>
        public string coupon_start_time {
            get {
                return this.coupon_start_timeField;
            }
            set {
                this.coupon_start_timeField = value;
            }
        }
        
        /// <remarks/>
        public long coupon_total_count {
            get {
                return this.coupon_total_countField;
            }
            set {
                this.coupon_total_countField = value;
            }
        }
        
        /// <remarks/>
        public string item_description {
            get {
                return this.item_descriptionField;
            }
            set {
                this.item_descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string item_url {
            get {
                return this.item_urlField;
            }
            set {
                this.item_urlField = value;
            }
        }
        
        /// <remarks/>
        public string nick {
            get {
                return this.nickField;
            }
            set {
                this.nickField = value;
            }
        }
        
        /// <remarks/>
        public long num_iid {
            get {
                return this.num_iidField;
            }
            set {
                this.num_iidField = value;
            }
        }
        
        /// <remarks/>
        public string pict_url {
            get {
                return this.pict_urlField;
            }
            set {
                this.pict_urlField = value;
            }
        }
        
        /// <remarks/>
        public long seller_id {
            get {
                return this.seller_idField;
            }
            set {
                this.seller_idField = value;
            }
        }
        
        /// <remarks/>
        public string shop_title {
            get {
                return this.shop_titleField;
            }
            set {
                this.shop_titleField = value;
            }
        }
        
        /// <remarks/>
        public string[] small_images {
            get {
                return this.small_imagesField;
            }
            set {
                this.small_imagesField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public long user_type {
            get {
                return this.user_typeField;
            }
            set {
                this.user_typeField = value;
            }
        }
        
        /// <remarks/>
        public long volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
            }
        }
        
        /// <remarks/>
        public string zk_final_price {
            get {
                return this.zk_final_priceField;
            }
            set {
                this.zk_final_priceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NTbkItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TbkCouponDomain))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class TopObject {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NTbkItem : TopObject {
        
        private string click_urlField;
        
        private string item_urlField;
        
        private string nickField;
        
        private long num_iidField;
        
        private string pict_urlField;
        
        private string provcityField;
        
        private string reserve_priceField;
        
        private long seller_idField;
        
        private string shop_titleField;
        
        private string[] small_imagesField;
        
        private string titleField;
        
        private string tk_rateField;
        
        private long user_typeField;
        
        private long volumeField;
        
        private string zk_final_priceField;
        
        private string zk_final_price_wapField;
        
        /// <remarks/>
        public string click_url {
            get {
                return this.click_urlField;
            }
            set {
                this.click_urlField = value;
            }
        }
        
        /// <remarks/>
        public string item_url {
            get {
                return this.item_urlField;
            }
            set {
                this.item_urlField = value;
            }
        }
        
        /// <remarks/>
        public string nick {
            get {
                return this.nickField;
            }
            set {
                this.nickField = value;
            }
        }
        
        /// <remarks/>
        public long num_iid {
            get {
                return this.num_iidField;
            }
            set {
                this.num_iidField = value;
            }
        }
        
        /// <remarks/>
        public string pict_url {
            get {
                return this.pict_urlField;
            }
            set {
                this.pict_urlField = value;
            }
        }
        
        /// <remarks/>
        public string provcity {
            get {
                return this.provcityField;
            }
            set {
                this.provcityField = value;
            }
        }
        
        /// <remarks/>
        public string reserve_price {
            get {
                return this.reserve_priceField;
            }
            set {
                this.reserve_priceField = value;
            }
        }
        
        /// <remarks/>
        public long seller_id {
            get {
                return this.seller_idField;
            }
            set {
                this.seller_idField = value;
            }
        }
        
        /// <remarks/>
        public string shop_title {
            get {
                return this.shop_titleField;
            }
            set {
                this.shop_titleField = value;
            }
        }
        
        /// <remarks/>
        public string[] small_images {
            get {
                return this.small_imagesField;
            }
            set {
                this.small_imagesField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string tk_rate {
            get {
                return this.tk_rateField;
            }
            set {
                this.tk_rateField = value;
            }
        }
        
        /// <remarks/>
        public long user_type {
            get {
                return this.user_typeField;
            }
            set {
                this.user_typeField = value;
            }
        }
        
        /// <remarks/>
        public long volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
            }
        }
        
        /// <remarks/>
        public string zk_final_price {
            get {
                return this.zk_final_priceField;
            }
            set {
                this.zk_final_priceField = value;
            }
        }
        
        /// <remarks/>
        public string zk_final_price_wap {
            get {
                return this.zk_final_price_wapField;
            }
            set {
                this.zk_final_price_wapField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SearchCouponCompletedEventHandler(object sender, SearchCouponCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchCouponCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchCouponCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SearchCouponRSCompletedEventHandler(object sender, SearchCouponRSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchCouponRSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchCouponRSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TbkCouponDomain[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TbkCouponDomain[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetTaoCodeCompletedEventHandler(object sender, GetTaoCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTaoCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTaoCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetItemDetailCompletedEventHandler(object sender, GetItemDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetItemDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetItemDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NTbkItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NTbkItem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetItemDetailJsonCompletedEventHandler(object sender, GetItemDetailJsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetItemDetailJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetItemDetailJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591